version: '3.7'

services:
  nginx-le:
    image: bastidest/nginx-letsencrypt:${NGINX_BASE_VERSION}
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - NGINX_BASE_VERSION=${NGINX_BASE_VERSION}
    volumes:
      - ./example/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./example/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx-le/letsencrypt/:/etc/letsencrypt/
    environment:
      - NGINX_LE_DOMAINS=test.hiebl.cc
      - NGINX_LE_EMAIL=3hiebl@gmail.com
      - NGINX_LE_DISABLE=1
      # - NGINX_LE_TEST_CERT=1
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
