name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y curl jq
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push all docker images
      run: DOCKER_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" DOCKER_PASSWORD="${{ secrets.DOCKERHUB_TOKEN }}" ./matrix-build.sh
